### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kexanone** [cen-mod/Medical#3]
- [ ] Replace health and resilience hit zone by medical state machine that also includes cardiac arrest as a new state.
- [ ] Medical menu (Possibility to do treatments on others via GUI)
- [ ] Advanced wounds (Reopening, wound types, different bandages)
- [ ] Replace autoregeneration of wounds by adding stitching as treatment
- [ ] Rework broken bones (increase handicap, add splints)
- [ ] Tweaking hit zones and bleeding to increase realism (_e.g._ femoral artery)
- [ ] Improved visuals of treatments (tourniquets and splits attached to patients)
- [ ] Restrict use of medical items by introducing traits
