### ISSUE TITLE
Medical state machine

### ISSUE THREAD

**Issue by Kexanone** [cen-mod/Medical#4]
**Goals:**
- Replace health and resilience hit zones by a medical state machine (following closely [ACE](https://github.com/acemod/ACE3/blob/master/addons/medical_statemachine/Statemachine.hpp))
- Add cardiac arrest as a new state

**Tasks:**
- [ ] Implement base classes for state machine (#5)
- [ ] Implement the core `OnState` function ([fnc_handleUnitVitals.sqf](https://github.com/acemod/ACE3/blob/master/addons/medical_vitals/functions/fnc_handleUnitVitals.sqf) in ACE)
- [ ] Implement the states including `OnState` handlings:
  - [ ] `Default`
  - [ ] `Injured`
  - [ ] `Unconscious`
  - [ ] `CardiacArrest`
  - [ ] `FatalInjury`
  - [ ] `Dead`
- [ ] Implement the transitions including events and actions that trigger them:
  - [ ] `Injured`: `Default` -> `Injured`
  - [ ] `CriticalInjuryOrVitals`: `Default` -> `Unconscious`
  - [ ] `FatalVitals`: `Default` -> `CardiacArrest`
  - [ ] `FatalInjury`: `Default` -> `FatalInjury`
  - [ ] `FullHeal`: `Injured` -> `Default`
  - [ ] `CriticalInjuryOrVitals`: `Injured` -> `Unconscious`
  - [ ] `FatalVitals`: `Injured` -> `CardiacArrest`
  - [ ] `FatalInjury`: `Injured` -> `FatalInjury`
  - [ ] `WakeUp`: `Unconscious` -> `Injured`
  - [ ] `FatalTransitions`: `Unconscious` -> `CardiacArrest`
  - [ ] `FatalInjury`: `Unconscious` -> `FatalInjury`
  - [ ] `DeathAI`: `Unconscious` -> `Dead`
  - [ ] `Reanimation`: `CardiacArrest` -> `Unconscious`
  - [ ] `DeathAI`: `CardiacArrest` -> `Dead`
  - [ ] `Timeout`: `CardiacArrest` -> `Dead`
  - [ ] `Execution`: `CardiacArrest` -> `Dead`
  - [ ] `Bleedout`: `CardiacArrest` -> `Dead`
  - [ ] `SecondChance`: `FatalInjury` -> `CardiacArrest`
  - [ ] `Death`: `FatalInjury` -> `Dead`
- [ ] Implement state machine clockwork (see [CBA](https://github.com/CBATeam/CBA_A3/blob/master/addons/statemachine/fnc_clockwork.sqf)) (#5)
- [ ] _TBD_

**Comment by Kexanone** [comment]
Closed in favor of https://github.com/orgs/cen-mod/projects/1
